#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#
##############################################################################

# Resolve application home
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*-> }
    case $link in
        /*) app_path=$link ;;
        *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME=Gradle
APP_BASE_NAME=${0##*/}

# Add default JVM options here.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Maximum file descriptors
MAX_FD=maximum

warn () {
    echo "$*" >&2
}

die () {
    echo >&2
    echo "$*" >&2
    echo >&2
    exit 1
}

# OS specific flags
cygwin=false
msys=false
darwin=false
nonstop=false

case "`uname`" in
    CYGWIN* ) cygwin=true ;;
    Darwin* ) darwin=true ;;
    MSYS* | MINGW* ) msys=true ;;
    NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Locate JAVA
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME"/bin/java ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no Java found."
fi

# Increase ulimit
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    if [ "$MAX_FD" = "maximum" ]; then
        MAX_FD=$( ulimit -H -n ) || warn "Could not query file descriptor limit"
    fi

    case $MAX_FD in
        '' | soft) : ;;
        *) ulimit -n "$MAX_FD" || warn "Could not set ulimit" ;;
    esac
fi


# Cygwin/MSYS path conversions
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )

    for arg do
        case $arg in
            -*) ;;
            /?*) t=${arg#/}
                 t=/${t%%/*}
                 [ -e "$t" ] && arg=$( cygpath --path --ignore --mixed "$arg" )
            ;;
        esac
        shift
        set -- "$@" "$arg"
    done
fi

# Apply JVM options
set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

eval "set -- $(
    printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
    xargs -n1 |
    sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
    tr '\n' ' '
) \"\$@\""

##############################################################################
# >>>>>>>>>>>>>>>>     FIX TERMUX (ANDROID)     <<<<<<<<<<<<<<<<
##############################################################################

export JAVA_HOME="/data/data/com.termux/files/usr/lib/jvm/openjdk-17"
JAVACMD="/data/data/com.termux/files/usr/lib/jvm/openjdk-17/bin/java"

##############################################################################

exec "$JAVACMD" "$@"