#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*-> }
    case $link in
        /*) app_path=$link ;;
        *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
APP_NAME=Gradle
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
MAX_FD=maximum

warn () { echo "$*" >&2; }
die () { echo >&2; echo "$*" >&2; echo >&2; exit 1; }

cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
    CYGWIN* ) cygwin=true ;;
    Darwin* ) darwin=true ;;
    MSYS* | MINGW* ) msys=true ;;
    NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Java command
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and java not found."
fi

# Increase max file descriptors
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    if [ "$MAX_FD" = "maximum" ]; then
        MAX_FD=$( ulimit -H -n ) || warn "Could not query file descriptor limit"
    fi
    case $MAX_FD in
        '' | soft) : ;;
        *) ulimit -n "$MAX_FD" || warn "Could not set ulimit" ;;
    esac
fi

# Cygwin/MSYS path conversion
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )
    for arg do
        case $arg in
            -*) ;;
            /?*) t=${arg#/}; t=/${t%%/*}; [ -e "$t" ] && arg=$( cygpath --path --ignore --mixed "$arg" ) ;;
        esac
        shift
        set -- "$@" "$arg"
    done
fi

# Arguments
set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

eval "set -- $(
    printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
    xargs -n1 |
    sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
    tr '\n' ' '
) \"\$@\""

exec "$JAVACMD" "$@"